# Generated by Django 3.1.4 on 2021-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teamsconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamsconfig',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
