# Generated by Django 3.1.4 on 2021-02-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_intent_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
