# Generated by Django 3.1.4 on 2021-02-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_agent_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='aad_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
