# Generated by Django 3.1.4 on 2021-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_userinfo_aad_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=100)),
                ('parameters', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
