# Generated by Django 3.1.4 on 2021-02-10 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_conversationparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 19, 13, 11, 256436)),
        ),
    ]
