# Generated by Django 3.1.4 on 2021-02-10 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20210210_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='conversation_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 10, 19, 25, 57, 520632)),
        ),
    ]
