# Generated by Django 3.1.4 on 2021-02-11 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_auto_20210210_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 10, 34, 34, 428335)),
        ),
    ]
