# Generated by Django 3.1.4 on 2021-02-15 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_auto_20210211_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitiesParsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(max_length=255)),
                ('entity_synonyms', models.JSONField(blank=True, default=list, null=True)),
                ('entity_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 10, 37, 44, 184052)),
        ),
    ]
