# Generated by Django 3.1.4 on 2021-02-18 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20210215_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('useremail', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 15, 7, 14, 582938)),
        ),
    ]
