# Generated by Django 3.1.4 on 2021-02-26 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20210218_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 10, 41, 12, 890886)),
        ),
    ]
