# Generated by Django 3.1.4 on 2021-02-26 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_auto_20210226_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 11, 28, 3, 770769)),
        ),
    ]
