# Generated by Django 3.1.4 on 2021-03-02 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_auto_20210226_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 16, 15, 52, 876853)),
        ),
    ]
