# Generated by Django 3.1.4 on 2021-03-05 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_auto_20210302_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 5, 13, 10, 31, 964312)),
        ),
    ]
