# Generated by Django 3.1.4 on 2021-09-15 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_auto_20210831_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 15, 12, 51, 41, 95496)),
        ),
    ]
