# Generated by Django 3.1.4 on 2022-07-07 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_auto_20210915_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 12, 9, 48, 993741)),
        ),
    ]
