# Generated by Django 3.1.4 on 2022-07-15 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_auto_20220707_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 15, 11, 29, 35, 565024)),
        ),
    ]
