# Generated by Django 3.1.4 on 2022-07-18 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_auto_20220715_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 5, 21, 9, 65840)),
        ),
    ]
