# Generated by Django 3.1.4 on 2022-09-30 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0037_auto_20220930_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 12, 6, 44, 169360)),
        ),
    ]
