# Generated by Django 3.1.4 on 2022-09-30 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0039_auto_20220930_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 12, 37, 19, 801957)),
        ),
    ]
