# Generated by Django 3.1.4 on 2022-10-04 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0042_auto_20220930_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 11, 21, 24, 97349)),
        ),
    ]
