# Generated by Django 3.1.4 on 2022-10-04 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0044_auto_20221004_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 11, 52, 55, 346274)),
        ),
    ]
