# Generated by Django 3.1.4 on 2022-10-12 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0045_auto_20221004_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 12, 42, 33, 600869)),
        ),
    ]
