# Generated by Django 3.1.4 on 2024-06-03 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0046_auto_20221012_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 11, 30, 43, 984921)),
        ),
    ]
