# Generated by Django 3.1.4 on 2024-06-03 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0048_auto_20240603_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparameters',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 3, 14, 18, 57, 452900)),
        ),
    ]
