# Generated by Django 3.1.4 on 2021-02-26 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BotUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('info', models.JSONField(default=dict)),
                ('email', models.CharField(max_length=255)),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botPlatform.platform')),
            ],
        ),
    ]
