# Generated by Django 3.1.4 on 2021-04-08 08:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_bot_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('web_uid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('bot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.bot')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
