# Generated by Django 3.1.4 on 2021-04-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_webbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
