# Generated by Django 3.1.4 on 2022-07-18 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_bot_web_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='web_uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
