# Generated by Django 3.1.4 on 2021-09-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_agent_description'),
        ('botPlatform', '0002_auto_20210607_2114'),
        ('botData', '0003_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.CharField(max_length=10)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.bot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botPlatform.botuserinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
